layout_spectrum: 0.6896318
typography_spectrum: 0.2072781
color:
  saturation: 0.6246887
  lightness: 0.5759627
  brandStrength: 0.01057374
  rhythmicContrast: 0.4359958
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: CherryWeapon
